library(plotrix)
slices<- c(10,12,4,16,8)
pct<- (slices/sum(slices)*100)
lbls<- paste(c("US", "UK", "Australia", "Germany", "France")," ",pct,"%",sep = "" )
pie3D(slices, labels = lbls, main = "Simple Pie Chart", col = c(rainbow(5)), explode = 0.0)